# Generated by Django 5.2 on 2025-05-09 11:53

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workers",
            fields=[
                ("worker_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("father_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "work_phone",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("password", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
                "db_table": "workers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ListPositions",
            fields=[
                ("position_id", models.AutoField(primary_key=True, serialize=False)),
                ("position_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "list_position",
                "verbose_name_plural": "list_positions",
                "db_table": "list_position",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Responsible",
            fields=[
                (
                    "responsible",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="responsible",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("surname", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("father_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="RU", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "responsible",
                "verbose_name_plural": "responsible",
                "db_table": "responsible",
                "managed": False,
            },
        ),
    ]
