# Generated by Django 5.1.1 on 2024-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListPositions',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'list_positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkersGroups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'workers group',
                'verbose_name_plural': 'workers groups',
                'db_table': 'worker_groups',
                'managed': False,
            },
        ),
    ]
