# Generated by Django 5.1.1 on 2024-11-03 10:58

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True)),
            ],
            options={
                'verbose_name': 'responsible',
                'verbose_name_plural': 'responsible',
                'db_table': 'responsible',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True)),
                ('work_phone', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'worker',
                'verbose_name_plural': 'workers',
                'db_table': 'workers',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='listpositions',
            table='list_position',
        ),
        migrations.AlterModelTable(
            name='workersgroups',
            table='workers_groups',
        ),
    ]
