# Generated by Django 5.1.1 on 2024-11-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_responsible_workers_alter_listpositions_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listpositions',
            options={'managed': False, 'verbose_name': 'list_position', 'verbose_name_plural': 'list_positions'},
        ),
    ]
