# Generated by Django 5.1.1 on 2024-11-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
