# Generated by Django 5.1.1 on 2024-12-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_users_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
