# Generated by Django 5.1.1 on 2024-12-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_delete_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkersGroups",
        ),
    ]
