# Generated by Django 5.1.1 on 2024-10-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
